### ISSUE TITLE
The example does not compile

### ISSUE THREAD

**Issue by francisp2** [grijjy/DelphiOpenSsl#3]
Missing files : 

 Grijjy.inc
 Grijjy.System
 Grijjy.BinaryCoding

**Comment by Morrismx** [comment]
> Missing files : 
> 
> 
> 
>  Grijjy.inc
> 
>  Grijjy.System
> 
>  Grijjy.BinaryCoding

This files are part of GrijjiFoundation

https://github.com/grijjy/GrijjyFoundation/tree/master
